import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationLoaderProvider } from "@/app/components/NavigationLoaderProvider";
import NavigationLoaderReset from "@/app/components/NavigationLoaderReset";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aoe4Community",
  description: "Generated by EpicoJackal",
  icons: {
    icon: "/logo_mettere.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationLoaderProvider>
          <NavigationLoaderReset />
          {children}
        </NavigationLoaderProvider>
        <SpeedInsights />
        <Analytics/>
      </body>
    </html>
  );
}