export type TerritoryOwner =
  | "aoeitalia"
  | "discord dei pezzenti"
  | "bimbe di kasiya"
  | "amedeoITA"
  | "la pescheria di taffuz";

export type TerritoryOwnershipEntry = {
  id: string;
  name: string;
  points: number;
  bonus: string;
  owner: TerritoryOwner;
};

export const territoryOwnership: TerritoryOwnershipEntry[] = [
  { id: "torino-1", name: "Torino", points: 1, bonus: "Assedio rapido: BO3", owner: "discord dei pezzenti" },
  { id: "vercelli-2", name: "Vercelli", points: 1, bonus: "Zona sacra: blind civ pick", owner: "discord dei pezzenti" },
  { id: "novara-3", name: "Novara", points: 1, bonus: "Ban civ: Mongols", owner: "amedeoITA" },
  { id: "cuneo-4", name: "Cuneo", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "amedeoITA" },
  { id: "asti-5", name: "Asti", points: 1, bonus: "Mappa fissa: Four Lakes", owner: "amedeoITA" },
  { id: "alessandria-6", name: "Alessandria", points: 1, bonus: "Assedio rapido: BO3", owner: "amedeoITA" },
  { id: "biella-7", name: "Biella", points: 1, bonus: "Zona sacra: blind civ pick", owner: "amedeoITA" },
  { id: "verbano-cusio-ossola-8", name: "Verbano Cusio Ossola", points: 1, bonus: "Mappa fissa: Lipany", owner: "discord dei pezzenti" },
  { id: "aosta-9", name: "Aosta", points: 2, bonus: "Mappa fissa: Lipany", owner: "discord dei pezzenti" },
  { id: "imperia-10", name: "Imperia", points: 2, bonus: "Bonus difesa +1 veto", owner: "discord dei pezzenti" },
  { id: "savona-11", name: "Savona", points: 2, bonus: "Fortezza: +1 punto dominio", owner: "amedeoITA" },
  { id: "genova-12", name: "Genova", points: 2, bonus: "Ban civ: English", owner: "amedeoITA" },
  { id: "la-spezia-13", name: "La Spezia", points: 2, bonus: "Ban civ: Rus", owner: "amedeoITA" },
  { id: "milano-14", name: "Milano", points: 2, bonus: "Mappa fissa: Lipany", owner: "amedeoITA" },
  { id: "bergamo-15", name: "Bergamo", points: 1, bonus: "Bonus difesa +1 veto", owner: "amedeoITA" },
  { id: "brescia-16", name: "Brescia", points: 1, bonus: "Ban civ: Rus", owner: "discord dei pezzenti" },
  { id: "como-17", name: "Como", points: 2, bonus: "Ban civ: Rus", owner: "discord dei pezzenti" },
  { id: "torino-18", name: "Torino", points: 3, bonus: "Ban civ: Rus", owner: "discord dei pezzenti" },
  { id: "lecco-19", name: "Lecco", points: 2, bonus: "Mappa fissa: Lipany", owner: "discord dei pezzenti" },
  { id: "lodi-20", name: "Lodi", points: 2, bonus: "Bonus difesa +1 veto", owner: "amedeoITA" },
  { id: "mantova-21", name: "Mantova", points: 2, bonus: "Fortezza: +1 punto dominio", owner: "amedeoITA" },
  { id: "monza-brianza-22", name: "Monza Brianza", points: 2, bonus: "Ban civ: English", owner: "amedeoITA" },
  { id: "pavia-23", name: "Pavia", points: 2, bonus: "Ban civ: Rus", owner: "amedeoITA" },
  { id: "sondrio-24", name: "Sondrio", points: 1, bonus: "Mappa fissa: Lipany", owner: "amedeoITA" },
  { id: "varese-25", name: "Varese", points: 1, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "bolzano-26", name: "Bolzano", points: 2, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "trento-27", name: "Trento", points: 2, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "verona-28", name: "Verona", points: 3, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "vicenza-29", name: "Vicenza", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "discord dei pezzenti" },
  { id: "belluno-30", name: "Belluno", points: 3, bonus: "Mappa fissa: Four Lakes", owner: "amedeoITA" },
  { id: "treviso-31", name: "Treviso", points: 3, bonus: "Assedio rapido: BO3", owner: "amedeoITA" },
  { id: "venezia-32", name: "Venezia", points: 2, bonus: "Zona sacra: blind civ pick", owner: "amedeoITA" },
  { id: "padova-33", name: "Padova", points: 2, bonus: "Ban civ: Mongols", owner: "amedeoITA" },
  { id: "rovigo-34", name: "Rovigo", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "amedeoITA" },
  { id: "udine-35", name: "Udine", points: 1, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "gorizia-36", name: "Gorizia", points: 2, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "trieste-37", name: "Trieste", points: 2, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "pordenone-38", name: "Pordenone", points: 3, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "parma-39", name: "Parma", points: 3, bonus: "Ban civ: Mongols", owner: "discord dei pezzenti" },
  { id: "piacenza-40", name: "Piacenza", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "discord dei pezzenti" },
  { id: "reggio-emilia-41", name: "Reggio Emilia", points: 3, bonus: "Mappa fissa: Four Lakes", owner: "amedeoITA" },
  { id: "modena-42", name: "Modena", points: 3, bonus: "Assedio rapido: BO3", owner: "amedeoITA" },
  { id: "bologna-43", name: "Bologna", points: 2, bonus: "Zona sacra: blind civ pick", owner: "amedeoITA" },
  { id: "ferrara-44", name: "Ferrara", points: 2, bonus: "Ban civ: Mongols", owner: "amedeoITA" },
  { id: "ravenna-45", name: "Ravenna", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "aoeitalia" },
  { id: "forli-cesena-46", name: "Forli Cesena", points: 1, bonus: "Ban civ: Rus", owner: "la pescheria di taffuz" },
  { id: "rimini-47", name: "Rimini", points: 2, bonus: "Ban civ: Rus", owner: "la pescheria di taffuz" },
  { id: "massa-carrara-48", name: "Massa Carrara", points: 2, bonus: "Ban civ: Rus", owner: "la pescheria di taffuz" },
  { id: "lucca-49", name: "Lucca", points: 3, bonus: "Ban civ: Rus", owner: "discord dei pezzenti" },
  { id: "pistoia-50", name: "Pistoia", points: 3, bonus: "Ban civ: Rus", owner: "discord dei pezzenti" },
  { id: "firenze-51", name: "Firenze", points: 4, bonus: "Ban civ: Rus", owner: "discord dei pezzenti" },
  { id: "livorno-52", name: "Livorno", points: 4, bonus: "Mappa fissa: Lipany", owner: "amedeoITA" },
  { id: "pisa-53", name: "Pisa", points: 3, bonus: "Bonus difesa +1 veto", owner: "amedeoITA" },
  { id: "arezzo-54", name: "Arezzo", points: 3, bonus: "Fortezza: +1 punto dominio", owner: "aoeitalia" },
  { id: "siena-55", name: "Siena", points: 2, bonus: "Ban civ: English", owner: "aoeitalia" },
  { id: "grosseto-56", name: "Grosseto", points: 2, bonus: "Ban civ: Rus", owner: "aoeitalia" },
  { id: "prato-57", name: "Prato", points: 1, bonus: "Mappa fissa: Lipany", owner: "aoeitalia" },
  { id: "perugia-58", name: "Perugia", points: 1, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "terni-59", name: "Terni", points: 2, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "milano-60", name: "Milano", points: 3, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "ancona-61", name: "Ancona", points: 3, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "macerata-62", name: "Macerata", points: 3, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "fermo-63", name: "Fermo", points: 4, bonus: "Mappa fissa: Lipany", owner: "discord dei pezzenti" },
  { id: "ascoli-piceno-64", name: "Ascoli Piceno", points: 5, bonus: "Massimi +3 attacco +3 difesa", owner: "discord dei pezzenti" },
  { id: "rieti-65", name: "Rieti", points: 4, bonus: "Bonus difesa +1 veto", owner: "aoeitalia" },
  { id: "roma-66", name: "Roma", points: 3, bonus: "Fortezza: +1 punto dominio", owner: "aoeitalia" },
  { id: "latina-67", name: "Latina", points: 3, bonus: "Ban civ: English", owner: "aoeitalia" },
  { id: "napoli-68", name: "Napoli", points: 3, bonus: "Ban civ: Rus", owner: "aoeitalia" },
  { id: "l-aquila-69", name: "L Aquila", points: 2, bonus: "Mappa fissa: Lipany", owner: "aoeitalia" },
  { id: "teramo-70", name: "Teramo", points: 1, bonus: "Bonus difesa +1 veto", owner: "aoeitalia" },
  { id: "pescara-71", name: "Pescara", points: 1, bonus: "Fortezza: +1 punto dominio", owner: "la pescheria di taffuz" },
  { id: "chieti-72", name: "Chieti", points: 2, bonus: "Fortezza: +1 punto dominio", owner: "la pescheria di taffuz" },
  { id: "campobasso-73", name: "Campobasso", points: 2, bonus: "Fortezza: +1 punto dominio", owner: "la pescheria di taffuz" },
  { id: "isernia-74", name: "Isernia", points: 3, bonus: "Fortezza: +1 punto dominio", owner: "la pescheria di taffuz" },
  { id: "caserta-75", name: "Caserta", points: 3, bonus: "Fortezza: +1 punto dominio", owner: "la pescheria di taffuz" },
  { id: "benevento-76", name: "Benevento", points: 4, bonus: "Fortezza: +1 punto dominio", owner: "discord dei pezzenti" },
  { id: "napoli-77", name: "Napoli", points: 4, bonus: "Fortezza: +1 punto dominio", owner: "aoeitalia" },
  { id: "avellino-78", name: "Avellino", points: 3, bonus: "Ban civ: English", owner: "aoeitalia" },
  { id: "salerno-79", name: "Salerno", points: 3, bonus: "Ban civ: Rus", owner: "aoeitalia" },
  { id: "foggia-80", name: "Foggia", points: 2, bonus: "Mappa fissa: Lipany", owner: "aoeitalia" },
  { id: "barletta-andria-trani-81", name: "Barletta Andria Trani", points: 2, bonus: "Bonus difesa +1 veto", owner: "aoeitalia" },
  { id: "bari-82", name: "Bari", points: 1, bonus: "Fortezza: +1 punto dominio", owner: "aoeitalia" },
  { id: "taranto-83", name: "Taranto", points: 1, bonus: "Ban civ: Mongols", owner: "la pescheria di taffuz" },
  { id: "brindisi-84", name: "Brindisi", points: 2, bonus: "Ban civ: Mongols", owner: "la pescheria di taffuz" },
  { id: "lecce-85", name: "Lecce", points: 2, bonus: "Ban civ: Mongols", owner: "la pescheria di taffuz" },
  { id: "potenza-86", name: "Potenza", points: 3, bonus: "Ban civ: Mongols", owner: "la pescheria di taffuz" },
  { id: "matera-87", name: "Matera", points: 3, bonus: "Ban civ: Mongols", owner: "la pescheria di taffuz" },
  { id: "cosenza-88", name: "Cosenza", points: 3, bonus: "Ban civ: Mongols", owner: "bimbe di kasiya" },
  { id: "catanzaro-89", name: "Catanzaro", points: 3, bonus: "Ban civ: Mongols", owner: "bimbe di kasiya" },
  { id: "crotone-90", name: "Crotone", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "aoeitalia" },
  { id: "vibo-valentia-91", name: "Vibo Valentia", points: 2, bonus: "Mappa fissa: Four Lakes", owner: "aoeitalia" },
  { id: "reggio-calabria-92", name: "Reggio Calabria", points: 2, bonus: "Assedio rapido: BO3", owner: "aoeitalia" },
  { id: "trapani-93", name: "Trapani", points: 1, bonus: "Zona sacra: blind civ pick", owner: "aoeitalia" },
  { id: "palermo-94", name: "Palermo", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "la pescheria di taffuz" },
  { id: "messina-95", name: "Messina", points: 2, bonus: "Mappa fissa: Dry Arabia", owner: "la pescheria di taffuz" },
  { id: "agrigento-96", name: "Agrigento", points: 2, bonus: "Mappa fissa: Dry Arabia", owner: "la pescheria di taffuz" },
  { id: "caltanissetta-97", name: "Caltanissetta", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "la pescheria di taffuz" },
  { id: "enna-98", name: "Enna", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "catania-99", name: "Catania", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "ragusa-100", name: "Ragusa", points: 3, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "siracusa-101", name: "Siracusa", points: 2, bonus: "Mappa fissa: Four Lakes", owner: "aoeitalia" },
  { id: "sassari-102", name: "Sassari", points: 2, bonus: "Assedio rapido: BO3", owner: "aoeitalia" },
  { id: "nuoro-103", name: "Nuoro", points: 1, bonus: "Zona sacra: blind civ pick", owner: "aoeitalia" },
  { id: "oristano-104", name: "Oristano", points: 1, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "cagliari-105", name: "Cagliari", points: 2, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "sud-sardegna-106", name: "Sud Sardegna", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "ravenna-bis-107", name: "Ravenna Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "pisa-bis-108", name: "Pisa Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "salerno-bis-109", name: "Salerno Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "venezia-110", name: "Venezia", points: 3, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "bari-bis-111", name: "Bari Bis", points: 2, bonus: "Bonus difesa +1 veto", owner: "bimbe di kasiya" },
  { id: "roma-bis-112", name: "Roma Bis", points: 1, bonus: "Fortezza: +1 punto dominio", owner: "aoeitalia" },
  { id: "torino-bis-113", name: "Torino Bis", points: 1, bonus: "Mappa fissa: Lipany", owner: "la pescheria di taffuz" },
  { id: "milano-bis-114", name: "Milano Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "catania-bis-115", name: "Catania Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "genova-bis-116", name: "Genova Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "perugia-bis-117", name: "Perugia Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "lecce-bis-118", name: "Lecce Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "padova-bis-119", name: "Padova Bis", points: 2, bonus: "Mappa fissa: Lipany", owner: "bimbe di kasiya" },
  { id: "trento-bis-120", name: "Trento Bis", points: 1, bonus: "Bonus difesa +1 veto", owner: "bimbe di kasiya" },
  { id: "firenze-bis-121", name: "Firenze Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "ancona-bis-122", name: "Ancona Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "cosenza-bis-123", name: "Cosenza Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "lucca-bis-124", name: "Lucca Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "siena-bis-125", name: "Siena Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "prato-bis-126", name: "Prato Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
  { id: "udine-bis-127", name: "Udine Bis", points: 1, bonus: "Mappa fissa: Dry Arabia", owner: "bimbe di kasiya" },
];
